### ISSUE TITLE
Classes conflict css

### ISSUE THREAD

**Issue by scoch5** [CakeWP/block-options#387]
The name of the css classes used by the plugin is very generic (eg "w-full"), this creates several conflicts with css libraries such as tailwind and others. I believe it may be better to prefix all plugin classes to avoid theme conflicts.

Daniele

**Comment by munirkamal** [comment]
Hi @scoch5 

Thank you to report that. Those classes are actually part of the Extendify Templates Library that is integrated as an SDK and not coming from the EditorsKit codebase directly.

I will pass your feedback to the team.

Btw, you can disable the library if you don't intend to use it.

Thanks

**Comment by munirkamal** [comment]
@scoch5 

Can you confirm which version of EK are you using? As seems like this has already been updated? I get this response from the lead developer from Extendify.

> Are they using a really old version maybe? The class we use is .ext-w-full

**Comment by scoch5** [comment]
Hi @munirkamal,
I checked and with the latest version the problem no longer happens.

Thanks miller for your support.
