### ISSUE TITLE
Live reload preview just reloads over and over

### ISSUE THREAD

**Issue by cresharper** [CakeWP/block-options#392]
When it's clicked, it reloads the preview over and over and over again.

Why would this happen? I tried disabling different plugins and nothing works.

Sometimes it happens and sometimes it doesn't 

Happens on Chrome and Safari, WP version 5.8.3

**Comment by muneebahmed0346** [comment]
Thank you to report that, I am tagging it as a bug for the dev team to look into it
Note: This seems to be an issue with WP v5.8.3 & 5.9 as per my tests

Video Link : https://share.getcloudapp.com/2NuvldQA

**Comment by cresharper** [comment]
Hi, just following up on this issue - let me know the status, thanks!

**Comment by dev-hero** [comment]
@muneebahmed0346 I wanted to follow up on this bug and see where things are at? Thank you, in advance!

**Comment by munirkamal** [comment]
The live preview feature has been deprecated for now.
