### ISSUE TITLE
error in menu of website since update 1.34.3

### ISSUE THREAD

**Issue by Zorrito2** [CakeWP/block-options#472]
Yesterday, after update to Editorskit1.34.3, 2 items in the header menu on the website gave a strange name. Instead of the normal name of that menu tab 'activiteiten' appears '#843 No title'. 2 of the 6 tabs were infected. 
I restored a backup, tried again but the error stays. 
The website functions now without the latest update of Editorskit.
The Graphene theme is used.

**Comment by munirkamal** [comment]
Yes, that is a known bug now, as reported by other users. I am working on a fix. It is related to the "Hide Page Title" feature.

**Comment by Zorrito2** [comment]
Thnx

**Comment by munirkamal** [comment]
This should be fixed with the latest update. Kindly test and confirm.

**Comment by Zorrito2** [comment]
Hello Sir,

I updated Editorskit with the new version and I see that the problem is
solved.

Thanks

Op di 21 feb. 2023 om 09:45 schreef Munir Kamal ***@***.***>:

**Comment by munirkamal** [comment]
Glad to hear that. I am closing this issue now as it's been resolved.

I would appreciate it if you could take a moment to leave a review for the plugin here:
https://wordpress.org/support/plugin/block-options/reviews/#new-post

Thanks
